### ISSUE TITLE
Recommend modify line 187 of 02_proc-dwi.sh to include threshold for B=0 shell values & to deal with non integer shell values

### ISSUE THREAD

**Issue by MarkNelson86** [MICA-MNI/micapipe#10]
Current line will only remove shells with b values exactly equal to 0, and will return error on non-integer values. Wouldn't be able to handle the following case:
```
$ shells=($(mrinfo "$dwi_n4" -shell_bvalues))
$ echo ${#shells[@]}
   4

$ for i in "${!shells[@]}"; do echo ${shells[i]}; done
   5
   299.5
   699.875
   1996.61
```
Suggest replacing line 187 with:

```
$ thr=15
$ for i in "${!shells[@]}"; do if [ ${shells[i]%.*} -le $thr ]; then unset 'shells[i]'; fi; done
$ echo ${#shells[@]}
   3
```

**Comment by rcruces** [comment]
Hi Mark, 

Thank you once again for this observation, we are close to our first release version and these details are very important. I already implemented your suggestion in the latest commit [b443425](https://github.com/MICA-MNI/micapipe/commit/b443425af840babd6fd7c3d5fc8694818ddf0f06). 

best!
