### ISSUE TITLE
realpath No such file or directory

### ISSUE THREAD

**Issue by BrianYahoo** [MICA-MNI/micapipe#100]
**I tried to use micapipe as follows:**

docker run -ti --rm \
    micalab/micapipe:v0.2.2 \
        -bids '../fMRI/bids' \
        -out '../fMRI/prop' \
        -fs_licence '../../license.txt' \
        -sub 01 \
        -proc_structural \
        -proc_surf \
        -post_structural \
        -proc_func

**but I get these errors:**

realpath: ../fMRI/prop: No such file or directory
realpath: ../fMRI/bids: No such file or directory

-------------------------------------------------------------

[ ERROR ]..... 01 was not found on the BIDS directory
         Check ls /sub-01

-------------------------------------------------------------

**But actually this directory does exist, I don't know how to fix this bug. What's wrong with my code?**

**Comment by rcruces** [comment]
Hi, in order to run the `docker` container your directories must have other read and write permissions and they must me mounted on the container with `-v`. See the documentation for an example:

https://micapipe.readthedocs.io/en/latest/pages/01.install/index.html
