### ISSUE TITLE
How to Specify the data directory?

### ISSUE THREAD

**Issue by BrianYahoo** [MICA-MNI/micapipe#101]
When I want to specify the bids directory as **"./bids"**, and I'm sure this **"./bids/sub-01/ses-01"** does exist

In the terminal line, I wrote **"docker run -ti --rm micalab/micapipe:v0.2.2 -bids ./bids -out ./prop -sub 01 -ses 01 -proc_structural"**.

Then it actually runs **"micapipe -bids ./bids -out ./prop -sub 01 -ses 01 -proc_structural"**, which is correct.

However, the OUTPUT is completely confusing because it reports

**_[ ERROR ]..... 01 was not found on the BIDS directory
         Check ls /home/mica/bids/sub-01/ses-01_**

Why is micapipe doing at this **"/home/mica/bids"** directory? I don't know how to specify the working directory to a **local path**, could anyone help me? Because this pipeline seems really powerful so I really want to learn how to use it!

**Comment by BrianYahoo** [comment]
When I tried input the absolute path of a directory as below:
**"micapipe -bids /data/bryang/human/WenZ/fMRI/bids -out /data/bryang/human/WenZ/fMRI/prop -sub 01 -ses 01 -proc_structural"**

The OUTPUT is still confusing because these two directory do exist:
**realpath: /data/bryang/human/WenZ/fMRI/prop: No such file or directory
realpath: /data/bryang/human/WenZ/fMRI/bids: No such file or directory**
and
**[ ERROR ]..... 01 was not found on the BIDS directory
         Check ls /sub-01/ses-01**

Therefore I'm done, that's as far as I can go.

**Comment by rcruces** [comment]
This issue is related to the issue #100, I will close this and continue there. It is highly likely that by mounting correctly the directories with `-v` will fix it.
