### ISSUE TITLE
Adding translation step improves ANTs registration in some datasets

### ISSUE THREAD

**Issue by MarkNelson86** [MICA-MNI/micapipe#102]
Unless all MRI images in a multimodal analysis are pretty well aligned to start, we've noticed that the addition of a simple translation step to align images by their geometric center improves registration with ANTs. It's a simple add-on and should only help registration. Here's an example:

```
# [fixedImage,movingImage,initializationFeature]
        centeralign="[${T1nativepro_brain},${dwi_b0},0]"                                                                        
      
# AFFINE: dwi to T1w
    antsRegistrationSyN.sh -d 3 -f "$T1nativepro_brain" -m "$dwi_b0"  \ 
             -o "$str_dwi_affine" -t a -n "$threads" -p d  \ 
             -i ${centeralign}

# Apply T1w to dwi affine transformation
    antsApplyTransforms -d 3 -i "$T1nativepro" -r "$dwi_b0"  \
             -t ["$mat_dwi_affine",1] -o "$T1nativepro_in_dwi" -v -u int

```

  This addition also helped improve our T1w-func registration.

**Comment by rcruces** [comment]
Thank you for your comment. This enhancement is included in our recently released version  [v0.2.3](https://github.com/MICA-MNI/micapipe/releases/tag/v0.2.3) which is already on our dockerhub:

```bash
docker pull micalab/micapipe:v0.2.3
```
