### ISSUE TITLE
"SINGLE" BIDS session error with proc_func

### ISSUE THREAD

**Issue by benjaminsipes** [MICA-MNI/micapipe#107]
*   **What is the current behavior?**  
    * Running proc_func on a BIDS dataset without specific session information produces an error. The error goes away if the standard BIDS session file structure is created.
![MICApipe_proc_func_error_report](https://github.com/MICA-MNI/micapipe/assets/87202817/112bd40c-5693-4eb2-aa5a-fd7a39b20327)
![MICApipe_proc_func_error](https://github.com/MICA-MNI/micapipe/assets/87202817/4260e9f4-3025-4596-b344-8ff12faf4da7)

*   **Please provide the steps to reproduce and if possible a minimal demo of the problem**  
    * Run the proc_func processing in a BIDS file structure such as `/BIDS_root/sub-1/func/sub-1_task-rest_bold.nii.gz`

*   **What is the expected behavior?**  
    * With all other processing lines, MICApipe adapts its paths to account for no session directory or file naming.

*   **Please tell us about your computing environment:**  
    * Run within a singularity container for micapipe v0.2.2

**Comment by rcruces** [comment]
Thank you for your comment. We fixed this error in the recently released version  [v0.2.3](https://github.com/MICA-MNI/micapipe/releases/tag/v0.2.3) which is already on our dockerhub:

```bash
docker pull micalab/micapipe:v0.2.3
```
