### ISSUE TITLE
"RepetitionTime is missing in"

### ISSUE THREAD

**Issue by hoptman** [MICA-MNI/micapipe#109]
*   **What are you trying to do?**  
*   **If you've tried running this with BrainSpace code already, how did you do so and what went wrong?**  
*   **Please tell us about your computing environment:**  
*   **Other information**  _

**Comment by hoptman** [comment]
Hi all,
I am enjoying the micapipe tool. I'm now trying to do the -proc_surf stage, but I now get the message "RepetitionTime is missing in", but when I look at the corresponding .json file, The RepetitionTime field is correctly populated.

I'm using micapipe v. 0.2.0 on Ubuntu Linux  20.04.
Thanks,
Matt

**Comment by rcruces** [comment]
can you please copy and paste the json file.

**Comment by hoptman** [comment]
Here you go:

{
  "InPlanePhaseEncodingDirectionDICOM": "COL",
  "ImageComments": "Unaliased_MB4_PE3",
  "ProcedureStepDescription": "RESEARCH_colcombe",
  "DeviceSerialNumber": "35390",
  "AcquisitionMatrixPE": 112,
  "ImageOrientationPatientDICOM": [
    1,
    0,
    0,
    0,
    0.991216,
    -0.132256
  ],
  "EffectiveEchoSpacing": 0.000689998,
  "TotalReadoutTime": 0.0765898,
  "ManufacturersModelName": "TrioTim",
  "ProtocolName": "REST_1400",
  "PhaseEncodingDirection": "j-",
  "BandwidthPerPixelPhaseEncode": 12.94,
  "RepetitionTime": 1.4,
  "SeriesNumber": 4,
  "PhaseEncodingSteps": 84,
  "MRAcquisitionType": "2D",
  "SliceThickness": 2,
  "AcquisitionNumber": 1,
  "InstitutionName": "Nathan_Kline_Institute_for_Psychiatric_Research",
  "DwellTime": 2.5e-06,
  "TxRefAmp": 312.696,
  "MultibandAccelerationFactor": 4,
  "DerivedVendorReportedEchoSpacing": 0.000689998,
  "SAR": 0.11055,
  "PulseSequenceDetails": "%CustomerSeq%_cmrr_mbep2d_bold",
  "ScanningSequence": "EP",
  "Manufacturer": "Siemens",
  "ConversionSoftware": "dcm2niix",
  "PercentPhaseFOV": 100,
  "ReconMatrixPE": 112,
  "FlipAngle": 65,
  "ConversionSoftwareVersion": "v1.0.20180403 GCC5.4.0",
  "SeriesDescription": "REST_1400",
  "PartialFourier": 0.75,
  "InstitutionAddress": "Old_Orangeburg_Road_140_Orangeburg_NY_US_10962",
  "ShimSetting": [
    -2298,
    -361,
    20600,
    387,
    523,
    467,
    -658,
    -155
  ],
  "AcquisitionTime": "13:35:3.482500",
  "SequenceName": "epfid2d1_112",
  "MagneticFieldStrength": 3,
  "TaskName": "rest",
  "SpacingBetweenSlices": 2,
  "ImageType": [
    "ORIGINAL",
    "PRIMARY",
    "M",
    "ND",
    "MOSAIC"
  ],
  "ReceiveCoilName": "32Ch_Head",
  "EchoTime": 0.03,
  "SequenceVariant": "SK",
  "PhaseResolution": 1,
  "BaseResolution": 112,
  "PixelBandwidth": 1786,
  "ScanOptions": "PFP_FS",
  "SoftwareVersions": "syngo_MR_B17",
  "StationName": "MRC35390",
  "Modality": "MR",
  "InstitutionalDepartmentName": "Department",
  "PatientPosition": "HFS",
  "SliceTiming": [
    0,
    0.615,
    1.2275,
    0.4375,
    1.0525,
    0.2625,
    0.8775,
    0.0875,
    0.7025,
    1.3175,
    0.525,
    1.14,
    0.35,
    0.965,
    0.175,
    0.79,
    0,
    0.615,
    1.2275,
    0.4375,
    1.0525,
    0.2625,
    0.8775,
    0.0875,
    0.7025,
    1.3175,
    0.525,
    1.14,
    0.35,
    0.965,
    0.175,
    0.79,
    0,
    0.615,
    1.2275,
    0.4375,
    1.0525,
    0.2625,
    0.8775,
    0.0875,
    0.7025,
    1.3175,
    0.525,
    1.14,
    0.35,
    0.965,
    0.175,
    0.79,
    0,
    0.615,
    1.2275,
    0.4375,
    1.0525,
    0.2625,
    0.8775,
    0.0875,
    0.7025,
    1.3175,
    0.525,
    1.14,
    0.35,
    0.965,
    0.175,
    0.79
  ]
}

**Comment by hoptman** [comment]
Hi again,
I figured out that I had named the file incorrectly (I had specified it using -mainScanStr).  Sorry to bother you!
Best wishes,
Matt
