### ISSUE TITLE
02_proc-dwi.sh fails to find nifti_capture.py

### ISSUE THREAD

**Issue by GabrielPelletier** [MICA-MNI/micapipe#14]
*   **What is the current behavior?** 
The call to nifti_capture.py during dwi processing, in 02_proc-dwi.sh at lines 285 and 304 fails (file not found).
  
*   **What is the expected behavior?**  
Call to nifti_capture.py should run smoothly, which can probably be solved by adding the full path to this script, as this was done in release 0.1.1 for micapipe_qc:
`Do_cmd ${MICAPIPE}/functions/nifti_capture.py ...`

**Comment by rcruces** [comment]
You are right, this could lead to unexpected behavior if `${MICAPIPE}/functions` is not declared in your `PATH`.  I added the full path to `nifti_capture.py` in the latest commit: https://github.com/MICA-MNI/micapipe/commit/28c6e9a61a3a6109c43d9858f360843518bdad24

thank you
