### ISSUE TITLE
nilearn is not listed in Dependencies

### ISSUE THREAD

**Issue by GabrielPelletier** [MICA-MNI/micapipe#15]
*   **What is the current behaviour?**  
The python module nilearn is not listed with the Dependencies in the documentation, but it seems to be needed for -proc_dwi, seeing that I got the following message in the proc_dwi_*.e log file:
`
Traceback (most recent call last):
  File "/fellows/fellows2/gabrielp/micapipe/functions/nifti_capture.py", line 33, in <module>
    from nilearn import plotting
ModuleNotFoundError: No module named 'nilearn'
`
It should be added to the list.

**Comment by rcruces** [comment]
Hi GabrielPelletier,

good catch!, I already added nilearn to the list in the latest update to README, and I double checked that we included it in the docket container!!

thank you
