### ISSUE TITLE
Issue with naming of str_dwi_affine/mat_dwi_affine not consistent between 02_proc-dwi.sh and 03_SC.sh

### ISSUE THREAD

**Issue by GabrielPelletier** [MICA-MNI/micapipe#18]
*   **What is the current behavior?**  
A change was made to 02_proc-dwi.sh in commit 29924fb but was not reflected in 03_SC.sh and causes problems.

In 02_proc-dwi.sh, this:
`str_dwi_affine="${dir_warp}/${idBIDS}_space-dwi_from-dwi_to-nativepro_mode-image_desc-"`
`mat_dwi_affine="${str_dwi_affine}0GenericAffine.mat"`

Was changed to:
`str_dwi_affine="${dir_warp}/${idBIDS}_space-dwi_from-dwi_to-nativepro_mode-image_desc-affine_"`
`mat_dwi_affine="${str_dwi_affine}0GenericAffine.mat"`

However, 03_SC.sh still looks for:
str_dwi_affine="${dir_warp}/${idBIDS}_space-dwi_from-dwi_to-nativepro_mode-image_desc-"
mat_dwi_affine="${str_dwi_affine}0GenericAffine.mat"

And throws an error at this line:
`if [ ! -f "$mat_dwi_affine" ]; then Error "Subject $id doesn't have an affine mat from T1nativepro to DWI space:\n\t\tRUN -proc_dwi"; exit; fi`

Because I have this file in my xmf/ directory:
`sub-05423_space-dwi_from-dwi_to-nativepro_mode-image_desc-affine_0GenericAffine.mat`

and not this one:
`sub-05423_space-dwi_from-dwi_to-nativepro_mode-image_desc-0GenericAffine.mat`

This prevents SC from running.

*   **What is the expected behavior?**  
I suppose that 03_SC.sh should look for:
`str_dwi_affine="${dir_warp}/${idBIDS}_space-dwi_from-dwi_to-nativepro_mode-image_desc-affine_"`
`mat_dwi_affine="${str_dwi_affine}0GenericAffine.mat"`

**Comment by rcruces** [comment]
Hello, thank you for the observation, now the names match in both scripts and in the tutorials! 
This issue was fixed in the following commit: https://github.com/MICA-MNI/micapipe/commit/1dd997a10b6d868da360258d220bd022f83b748e
