### ISSUE TITLE
Freesurfer license not found

### ISSUE THREAD

**Issue by alffajardo** [MICA-MNI/micapipe#20]
Hi,

I am running the conteinerized version of micapipe with singularity CE 3.5.3 in a cluster grid.  It is worth noting that I pulled the container from the dockerhub : `singularity pull micapipe.sif docker://micalab/micapipe:latest`.

At some point of  the `freesurfer_proc` crashes because the path to the license.txt file is missing (I clip a screenshot of the logs), and therefore all the subsequent steps fail. I have a freesurfer license but I don't know how to get it into the container. Is there a way to achieve this? Thanks in advance
![image](https://user-images.githubusercontent.com/14364623/137038980-58da506f-8c51-4746-93d8-d19e1c0db2ba.png)

**Comment by PeerHerholz** [comment]
Ahoi hoi @alffajardo,

as you already noticed: the required `Freesurfer license` file is not included in the `micapipe` image and needs to be provided via a respective mapping. I'm currently working on the `usage` information that will outline these things, sorry it's not up yet! In the meantime you could try adding the following to your command:

`-B /path/to/your/local/freesurfer-license:/opt/freesurfer-6.0.0/license.txt`  

As with all other things concerning mapping between host and container, the path you map should have the right access permissions. 

HTH, sorry again. 

Cheers, Peer
