### ISSUE TITLE
Nilearn dependency doesn't exist?

### ISSUE THREAD

**Issue by alffajardo** [MICA-MNI/micapipe#21]
I am testing micapipe in a sigularity container in a cluster grid.When I look at the logs in several steps (e.g `dwi_proc`) there are several error messages related to missing python dependencies such as nilearn. I clip an example of this error. Am I doing something wrong? how should I prevent/solve this error?

Thanks in advance

PD: Here is an example of the way I run the code. I followed the tutorial example of the sudemex_conn database  depicted in the documentation
```
singularity run --cleanenv  -B /mnt:/mnt -H $PWD singularity/micapipe_29092021.simg \
 -bids /mnt/MD1200B/egarza/afajardo/sudmex_conn/ds003346-download -sub 010 \
 -out /mnt/MD1200B/egarza/afajardo/sudmex_conn -proc_structural -proc_freesurfer -post_structural \ 
-GD -Morphology \ 
-proc_dwi \
-dwi_main /mnt/MD1200B/egarza/afajardo/sudmex_conn/ds003346-download/sub-010/dwi/sub-010_dwi.nii.gz \  
-dwi_rpe  /mnt/MD1200B/egarza/afajardo/sudmex_conn/ds003346-download/sub-010/fmap/sub-010_dir-PA_run-01_epi.nii.gz -SC -proc_rsfmri \ 
-mainScanStr task-rest_bold \
 -fmri_rpe  /mnt/MD1200B/egarza/afajardo/sudmex_conn/ds003346-download/sub-010/fmap/sub-010_dir-PA_run-02_epi.nii.gz
-regress_WM_CSF \
-GSR \ 
-QC_subj |&  tee micapipe_prueba/prueba4_logs.txt  |& tee micapipe_prueba/prueba4_logs.txt \
```

![image](https://user-images.githubusercontent.com/14364623/137040544-5b4c3b53-f007-43ec-abb5-73cea563d4e4.png)

**Comment by PeerHerholz** [comment]
Ahoi hoi @alffajardo,

thx for the report! I'm sorry you're experiencing this issue, that's on me: the image on dockerhub wasn't updated accordingly after `nilearn` was added. Could you maybe pull the image again early next week and give it another  try?

Sorry again. Cheers, Peer
