### ISSUE TITLE
adding JuBrain parcellation

### ISSUE THREAD

**Issue by neuroimagingdatascience** [MICA-MNI/micapipe#23]
Hi Raul/Jess - together with Casey, we were discussing to incorporate the JuBrain parcellation into the default parcellations that are used for connectome generation in a future release of micapipe. She has already the parcellation in MNI152 but also fsaverage and conte69. The parcellation is partial (ie not all brain regions have a label) but this may nevertheless be useful to link micapipe with some of the julich projects for hiball etc. - what do you think?

**Comment by rcruces** [comment]
would be nice to develop an easier way to include any custom parcellation. Maybe a tutorial explaining how to create the surfaces and labels, and how to share them with the micapipe developers.

**Comment by rcruces** [comment]
We will evaluate the possibility to include custom or new parcellations on future releases @royj23

**Comment by rcruces** [comment]
This enhancement not be implemented in the pipeline. I will close the issue. If you want to work on it please feel free to re-open the issue.
