### ISSUE TITLE
Supply container for HPCs with older kernel versions

### ISSUE THREAD

**Issue by ajschadler12** [MICA-MNI/micapipe#28]
*   **What is the current behaviour?**  
    *   The converted singularity image does not run on an HPC cluster with CentOS 6.10 (kernel ver: `2.6.32`), posting the error: "`KERNEL TOO OLD`", indicating `2.6.32` is not supported by Ubuntu 18.04's version of glibc.
*   **What is the motivation / use case for changing the behaviour?**
    *   Backporting the container to either `ubuntu:xenial` or an earlier version of debian will allow researchers with older HPC environments to deploy and use the micapipe container.
*   **If relevant, please tell us about your computing environment:**  
    *    Kernel ver: `2.6.32`, Distro: `CentOS 6.10`
*   **Other information**

**Comment by rcruces** [comment]
Hi, 

As you mention in your comment, we don't have support for older kernels at the present moment. I think that a plausible solution would be to modify the [generate_micapipe_image.sh](https://github.com/MICA-MNI/micapipe/blob/master/generate_micapipe_images.sh) (line 8) and hope that all the software dependencies are still compatible with `ubuntu:xenial`. We encourage you to fork the repository and try to generate a new image with this kernel. However we can't tell if all the pipeline dependencies will be compatible with this kernel version. If you are willing to contribute to the pipeline with this image, we would add it with pleasure.

best.
