### ISSUE TITLE
Ran commands successfully but no results files generated

### ISSUE THREAD

**Issue by jhx9327** [MICA-MNI/micapipe#31]
Hi! 

I ran micapipe by docker with the following commands:
docker run -ti --rm \
-v /my_path/bids:/data:ro   \
-v /my_patht/micapipe/derivatives:/out   \
-v /my_path/micapipe/working_directory:/tmp \
-v /my_path/license.txt:/opt/freesurfer/license.txt  \
micalab/micapipe:latest  -bids /data -out /out  \
-proc_structural -sub 03 04 -threads 10 -tracts 10M

It seems that it ran successfully but there is no results generated under derivative and working_dirctory except these. The folders of freesurfer and sub-03 can not be opened or deleted. My input data is in BIDS format which can be used to fmriprep (so I guess it might not result from my data).
micapipe
├── derivatives
│   ├── freesurfer [error opening dir]
│   └── micapipe
│       ├── micapipe_processed_sub.csv
│       ├── pipeline-description.json
│       └── sub-03 [error opening dir]
└── working_directory

Thank you so much if you can give me any idea to deal with this. Happy holiday!

**Comment by rcruces** [comment]
I believe that this is a permission issue, and if you have problems creating the container it's better for you to contact your administrator. Here is more information regarding the container generation: [documentation](https://micapipe.readthedocs.io/en/latest/pages/01.install/index.html)
