### ISSUE TITLE
Add option to use the the ss3t_csd_beta1 algorithm for single-shelled data.

### ISSUE THREAD

**Issue by ajschadler12** [MICA-MNI/micapipe#33]
*   **What is the current behaviour?**  
    * When provided single-shelled data, micapipe uses the "single tissue constrained spherical deconvolution" algorithm for FOD generation.
*   **What is the motivation / use case for changing the behaviour?**  
    * [MRtri3Tissue](https://3tissue.github.io/) is a fork of MRtrix3 (by Dhollander) which extends the multi-tissue FOD algorithm to single-shelled acquisitions.
    * FOD generation for WM, GM, and CSF is performed using `3Tissue/bin/ss3t_csd_beta1`, on response functions generated using the `dhollander` algorithm.
    * The FODs can be used like normal in `tckgen`.

Since the program is still experimental, it may be best to turn on this functionality using a flag, e.g. `-do_ss3t_csd` (name taken from QSIprep).

**Comment by rcruces** [comment]
It's a great suggestion to extend the capabilities of our pipeline with this software. Again we encourage you to contribute with the development and implementation of new software and extended functionalities.
