### ISSUE TITLE
Missing commas in lut_aparc_mics.csv prevent automatic parsing

### ISSUE THREAD

**Issue by MarkNelson86** [MICA-MNI/micapipe#34]
Suggest adding 1 comma at the end of **lines 2 & 38** (L & R medial wall) to fix

**Comment by rcruces** [comment]
Thanks for the observation, this was fixed on master on the commit https://github.com/MICA-MNI/micapipe/commit/e72fa78a10b38d91ec7331289510a4babe98e210. However it will not be included on the docker yet.
