### ISSUE TITLE
conte69 surface problems

### ISSUE THREAD

**Issue by hoptman** [MICA-MNI/micapipe#35]
Hi all,
I'm trying to use mica-pipe on some of my data (especially the -SC, -Morphology, and -MPC modules). I am running into a problem, however. I am getting the Freesurfer license error, and I can't figure out why. I've moved it to my home directory and pointed to it, but no luck. I am running Ubuntu 16.04.4 LTS and have current versions of all of the software I need.

The bigger problem seems to be that I can't do anything involving the conte69 surfaces. Proc_structural works fine, and for freesurfer, I copied a prior run (from outside mica-pipe) to my derivatives/freesurfer subdirectory. In the subdirectory, I now see conte69, fsaverage, fsaverage5 and my subject directory. However, within the conte69 directory, I see only a surf subdirectory (_surf_) which contains lh.conte69.gii and rh.conte69.gii.  I have a feeling that this is a problem, but I'm not sure. In any event, it seems that the connectome modules are dependent on proper processing of the conte69 surfaces and registration of images to them. So I'm stuck.

Any help is appreciated!
Best wishes,
Matt

**Comment by roryjpiper** [comment]
Hi @hoptman -did you figure out the freesurfer license error? - I am getting the same when running:

docker run -ti --rm \
-v /Users/rorypiper/Desktop/mica-pipe-test/bids:/bids_dataset:ro \
-v /Users/rorypiper/Desktop/mica-pipe-test/out:/output_directory \
-v /Users/rorypiper/Desktop/mica-pipe-test/tmp:/tmp \
-v /Applications/freesurfer/license.txt:/opt/freesurfer-6.0.0/freesurfer_license_file.txt \
micalab/micapipe:latest \
    -out /output_directory \
    -sub 01 \
    -bids /bids_dataset \
    -proc_freesurfer -ses 01 \
    -nocleanup \

**Comment by hoptman** [comment]
> Hi @hoptman -did you figure out the freesurfer license error? - I am getting the same when running:
> 
> docker run -ti --rm -v /Users/rorypiper/Desktop/mica-pipe-test/bids:/bids_dataset:ro -v /Users/rorypiper/Desktop/mica-pipe-test/out:/output_directory -v /Users/rorypiper/Desktop/mica-pipe-test/tmp:/tmp -v /Applications/freesurfer/license.txt:/opt/freesurfer-6.0.0/freesurfer_license_file.txt micalab/micapipe:latest -out /output_directory -sub 01 -bids /bids_dataset -proc_freesurfer -ses 01 -nocleanup \

I don't know whether this should have worked or not, but I copied the license file to my bids_dataset directory and it worked.
