### ISSUE TITLE
Conte69 not generated from proc_structural

### ISSUE THREAD

**Issue by roryjpiper** [MICA-MNI/micapipe#36]
Hi MicaPipe team. Really excited to use this, but hit a problem with the output from the proc_sructural (and therefore cannot run the post_structural past step 3.

The proc_structural leaves me with an empty a Conte69 directory and therefore causes these issues in post_structural:

rorypiper @ MS00048528 Tue 15 Feb 2022 00:22:10 GMT:
COMMAND -->   wb_command -surface-resample /tmp/790_micapipe_post-struct_sub-385_ses-01preop/rh.white.surf.gii /Users/rorypiper/Desktop/sub-385/ses-01preop/out/micapipe/sub-385/ses-01preop/anat/surfaces/conte69/sub-385_ses-01preop_rh_sphereReg.surf.gii /Users/rorypiper/Documents/software/micapipe/surfaces/fs_LR-deformed_to-fsaverage.R.sphere.32k_fs_LR.surf.gii BARYCENTRIC /Users/rorypiper/Desktop/sub-385/ses-01preop/out/micapipe/sub-385/ses-01preop/anat/surfaces/conte69/sub-385_ses-01preop_space-conte69-32k_desc-rh_white.surf.gii  

While running:
/Applications/workbench/bin_macosx64/../macosx64_apps/wb_command.app/Contents/MacOS/wb_command -surface-resample /tmp/790_micapipe_post-struct_sub-385_ses-01preop/rh.white.surf.gii /Users/rorypiper/Desktop/sub-385/ses-01preop/out/micapipe/sub-385/ses-01preop/anat/surfaces/conte69/sub-385_ses-01preop_rh_sphereReg.surf.gii /Users/rorypiper/Documents/software/micapipe/surfaces/fs_LR-deformed_to-fsaverage.R.sphere.32k_fs_LR.surf.gii BARYCENTRIC /Users/rorypiper/Desktop/sub-385/ses-01preop/out/micapipe/sub-385/ses-01preop/anat/surfaces/conte69/sub-385_ses-01preop_space-conte69-32k_desc-rh_white.surf.gii

ERROR: NAME OF FILE: rh.white.surf.gii
PATH TO FILE: /tmp/790_micapipe_post-struct_sub-385_ses-01preop

File does not exist.

----

Please can you help?

**Comment by rcruces** [comment]
Hi, this might be due to a permission issue we had in our first release. We are building a new container with version `0.1.3`. Maybe you already found a solution. Sorry for the very late reply

**Comment by rcruces** [comment]
We invite you to use the new version that offers more flexibility, more robust registrations and surface based mapping.

v0.2.0 https://github.com/MICA-MNI/micapipe/releases/tag/v0.2.0
