### ISSUE TITLE
'Subject 01 doesn't have T1_nativepro warp to MNI152.'

### ISSUE THREAD

**Issue by roryjpiper** [MICA-MNI/micapipe#37]
Hi - I am trying to run mica-pipe via Docker. It has completed 'proc_structural', but will not let me run 'proc_dwi' due to the following error:

rorypiper@MS00048528 mica-pipe-test % docker run -ti --rm \
-v /Users/rorypiper/Desktop/mica-pipe-test/bids:/bids_dataset:ro \
-v /Users/rorypiper/Desktop/mica-pipe-test/out:/output_directory \
-v /Users/rorypiper/Desktop/mica-pipe-test/tmp:/tmp \
-v /Applications/freesurfer/license.txt:/opt/freesurfer-6.0.0/freesurfer_license_file.txt \
micalab/micapipe:latest \
    -out /output_directory \
    -sub 01 \
    -bids /bids_dataset \
-proc_dwi  -ses 01 \
 -nocleanup \

Some packages in this Docker container are non-free
If you are considering commercial use of this container, please consult the relevant license:
https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Licence
INFO: /root/matlab/startup.m does not exist ... creating
-------- freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c --------
Setting up environment for FreeSurfer/FS-FAST (and FSL)
FREESURFER_HOME   /opt/freesurfer-6.0.0
FSFAST_HOME       /opt/freesurfer-6.0.0/fsfast
FSF_OUTPUT_FORMAT nii.gz
SUBJECTS_DIR      /opt/freesurfer-6.0.0/subjects
MNI_DIR           /opt/freesurfer-6.0.0/mni
FSL_DIR           /opt/fsl-6.0.0

-------------------------------------------------------------
	MICA pipeline - (Version v0.1.1 'Roadrunner') 
		Subject: 01 Session: ses-01
-------------------------------------------------------------

[ WARNING ]..... fix was not found, ICA-FIX will be skipped 

[ INFO ]..... micapipe will use 6 threads for multicore processing 

[ INFO ]..... Subject 01 directory exist 

[ INFO ]..... Inputs of proc_dwi: 
		tmpDir     : 	/tmp
		dwi_main   : 	DEFAULT
		dwi_rpe    : 	DEFAULT
		rpe_all    : 	FALSE
		Affine only: 	FALSE
		Processing : 	LOCAL

**-------------------------------------------------------------

[ ERROR ]..... Subject 01 doesn't have T1_nativepro warp to MNI152.
		Run -proc_structural

-------------------------------------------------------------**

**Comment by roryjpiper** [comment]
@royj23 - have you encountered this before?

**Comment by rcruces** [comment]
Hi, I recomend you to pull the version v.0.1.2 from the docker hub. 

```
export DOCKER_CONTENT_TRUST=0
docker pull micalab/micapipe:v0.1.2

```

Then try to run again `-proc_struct` and `-proc_dwi` only. I don't see any issues with you freesurfer license.
