### ISSUE TITLE
MPC input

### ISSUE THREAD

**Issue by hoptman** [MICA-MNI/micapipe#40]
Hi all,
I have gotten everything to run except for the MPC stage. I am not sure what the input should be. I have a t1 weighted image, but no t2w.

The environment I'm using is Linux 16.04 LTS (xenial) with 24 processors.
Thanks,
Matt

**Comment by rcruces** [comment]
Hi Matt,

MPC's goal is to generate a microstructural profile covariance matrix of the cortex from a microstructural-sensitive MRI image, aka quantitative image (eg. T1map, T2starmap, MTR), or from a map generated from post processing data such as T1w/T2w. Also it's highly recommended to have a good resolution image (0.7mm or lower) and with a good SNR. MPC is an optional module and not all the datasets have an acquisition you could use with it. It's great that you got everything else running, good luck with your analysis!


For further information see:
Paquola C, Vos de Wael R, Wagstyl K, Bethlehem R, Seidlitz J, Hong S, Bullmore ET, Evans AC, Misic B, Margulies DS, Smallwood J, Bernhardt BC (2019) Dissociations between microstructural and functional hierarchies within regions of transmodal cortex. PLoS Biology, in press

Paquola C, Bethlehem RAI, Seidlitz J, Wagstyl K, Romero-Garcia, Whitaker KJ, Vos de Wael R, Williams GB, NSPN Consortium, Vertes PE, Bernhardt BC, Bullmore ET (2019). A moment of change: shifts in myeloarchitecture profiles characterize adolescent development of cortical gradients. Preprint: https://www.biorxiv.org/content/10.1101/706341v1
