### ISSUE TITLE
Incorrect bvalues returned with processed multishell sequence.

### ISSUE THREAD

**Issue by ajschadler12** [MICA-MNI/micapipe#41]
*   **What is the current behavior?**  The final processed dwi in a multishell sequence has incorrect bvalues for 1st and 2nd shells. Original shells were 500, 1000, and 4000. "New" shells are 62, 250, and 4000.
*   **Please provide the steps to reproduce and if possible a minimal demo of the problem**  Provide multishell acquisition and a reverse-PE b0 image. Confirm bvalues with `mrinfo -dwgrad $file`.
*   **What is the expected behavior?**  Final processed output should preserve original bvalues.
*   **Please tell us about your computing environment:**  Modified singularity container, running ubuntu 16.04 (xenial) and FS7.1.1.
*   **Other information**

Original bvals
```
0 500 500 500 500 500 500 500 500 500 500 500 501 500 500 500 1000 1000 1000 1000 1000 1000 1001 1000 1000 1001 1000 1001 1000 1001 1000 4000 4001 3999 3999 3999 3999 4002 4000 3999 4002 4002 4006 3998 4003 4001
```

Original bvecs
```
0.000 0.354 0.227 0.091 0.263 0.058 -0.281 0.269 -0.179 0.236 0.045 -0.063 0.090 -0.120 -0.283 0.119 0.500 0.322 0.129 0.372 0.082 -0.398 0.381 -0.253 0.334 0.064 -0.089 0.128 -0.170 -0.401 0.168 1.000 0.643 0.258 0.745 0.164 -0.796 0.761 -0.506 0.667 0.128 -0.178 0.255 -0.340 -0.801 0.336
0.000 0.000 0.271 0.109 -0.210 -0.179 -0.113 0.151 0.295 -0.056 -0.339 -0.317 -0.209 -0.260 0.116 0.015 0.000 0.383 0.153 -0.297 -0.254 -0.161 0.213 0.416 -0.079 -0.479 -0.449 -0.295 -0.368 0.165 0.021 0.000 0.766 0.307 -0.594 -0.507 -0.321 0.427 0.833 -0.158 -0.959 -0.898 -0.590 -0.736 0.329 0.043
0.000 0.000 0.000 0.324 0.107 0.299 0.181 0.173 0.079 0.257 0.090 -0.142 -0.271 0.207 0.177 -0.333 0.000 0.000 0.458 0.151 0.423 0.257 0.244 0.112 0.364 0.127 -0.202 -0.384 0.292 0.251 -0.470 0.000 0.000 0.916 0.303 0.846 0.513 0.489 0.224 0.728 0.254 -0.403 -0.767 0.585 0.501 -0.941
```

"New" bvals

```
0 62.658 62.485 62.56899999 62.35900001 62.403 62.2455 62.54550001 62.6535 62.4405 62.52299999 62.311 62.736222 62.4245 62.437 62.6375 250 250.373 249.814 249.394 250.169 250.374 250.316066 249.609 250.293 249.915666 250.326 251.115865 249.588 251.278027 249.565 4000 4001.820205 3998.476131 3997.68033 3997.644339 3998.304174 4004.285142 4000.404 3998.348163 4004.325162 4003.988994 4011.664484 3996.084958 4006.374529 4001.904226
```

**Comment by rcruces** [comment]
I assumed that the bvalues were automatically scaled by MRtrix3, see [b-value-scaling](https://mrtrix.readthedocs.io/en/latest/concepts/dw_scheme.html#b-value-scaling). Is this issue affecting the tractography (tract density image) of structural connectomes?

**Comment by ajschadler12** [comment]
I see, thank you for the explanation.
I will have to test that in the future. For now, will close the issue.
