### ISSUE TITLE
example docker command in documentation incorrectly specifies freesurfer license 

### ISSUE THREAD

**Issue by dkp** [MICA-MNI/micapipe#45]
A docker command that uses 
    `-v path/to/your/freesurfer_license_file.txt:/opt/freesurfer-6.0.0/freesurfer_license_file.txt \`
as specified in the documentation fails immediately saying that the freesurfer _license.txt_ cannot be found.
The correct bind mount appears to be as follows:
 `-v path/to/your/freesurfer_license_file.txt:/opt/freesurfer-6.0.0/license.txt \`

**Comment by PeerHerholz** [comment]
Hi @dkp,

thx for catching this, I think I made a copy-paste error. Sorry for this. We will update the docs respectively asap.

Cheers, Peer

**Comment by rcruces** [comment]
This issue was fixed in some point. see https://micapipe.readthedocs.io/en/latest/pages/01.install/index.html
