### ISSUE TITLE
Alternative distortion correction options

### ISSUE THREAD

**Issue by dkp** [MICA-MNI/micapipe#47]
fmriprep uses fieldmaps (magnitude and phasediff) to correct distortion in bold images. It also allows a simple RPE image of the main bold data.  Could you implement some of these alternatives?

Thank you!

**Comment by rcruces** [comment]
Hi, we are working to implement a single RPE of the main bold data in the upgraded release `0.2.0` however we still estimate that it will be ready in the next months. We are not planing to include magnitude and phasediff at any point due to the increase complexity in the implementation.

**Comment by rcruces** [comment]
We are currently working on a option to include fMRIprep clean outputs to our workflow. Please stay tuned
