### ISSUE TITLE
change output directory structure to be bids conform

### ISSUE THREAD

**Issue by PeerHerholz** [MICA-MNI/micapipe#5]
Ahoi hoi folks,

`mica-pipe` currently takes a `-bids` and a `-out` argument and subsequently creates a new directory with the name of the participant specified via `-sub` within `-out`. While it's kinda "`BIDS-y`", it's not `BIDS`-conform. Following the [BIDS derivatives](https://bids-specification.readthedocs.io/en/stable/05-derivatives/01-introduction.html), a new pipeline specific directory should be created under `derivatives` and within that a folder for each `participant`. Furthermore, a `pipeline description` and `json sidecar files` need to be generated. For example:

     bids_dataset
            derivatives
                  mica-pipe
                        pipeline-description.json
                        sub-001
                                sub-001_T1w_desc-preproc.nii.gz
                                sub-001_T1w_desc-preproc.json
            dataset_description.json
            participants.tsv
            participants.json
            sub-001
            sub-002

- [x] place outputs under `bids_dataset_root_folder/derivatives/micapipe`
- [x] add `pipeline_description.json`
- [x] add `json sidecar files`
- [ ] maybe: remove `-out` as `BIDS derivatives` specify where things should go and thus only `-bids` is needed

Happy to provide further information for any of this.

Cheers, Peer

**Comment by rcruces** [comment]
Dear Peer,

On our latest push, we tried to amended all this issues, we created json files for the main outputs, and the `pipeline_descrioption.json`. We are looking forward to have a BIDS app conformed pipeline.

thank you for this and for further suggestions

**Comment by dkp** [comment]
Thanks for the reply...it isn't clear to me how you support the separate derivatives option.  Do you mean I'm free to move derivatives AFTER running micapipe?

**Comment by PeerHerholz** [comment]
Hi @dkp,

it's not directly supported but as you outlined, you could simply move the `derivatives` directory (or only the `micapipe` parts) out of the source `BIDS` dataset.

Cheers, Peer
