### ISSUE TITLE
Mica reports that it couldn't find any dwi file

### ISSUE THREAD

**Issue by Neuro-en** [MICA-MNI/micapipe#50]
*   **What are you trying to do?**  
*   **If you've tried running this with BrainSpace code already, how did you do so and what went wrong?**  
*   **Please tell us about your computing environment:**  
*   **Other information**

**Comment by Neuro-en** [comment]
I have read the provided tutorials, my data is the same as cam-CAN. i attach the command that i have tried to run: 
docker run -ti --rm \
    -v /home/moslem/data:/bids_dataset:ro \
    -v /home/moslem/data/sub-A00056307/derivatives:/output_directory \
    -v /home/moslem/tmp:/tmp \
    -v /home/moslem/freesurfer/license.txt:/opt/freesurfer-6.0.0/license.txt \
    micalab/micapipe:latest \
     -sub A00056307 \
     -bids /bids_dataset \
     -out /output_directory \
     -ses BAS1 \
     -proc_structural -t1wStr T1w \
           -proc_freesurfer -hires \
           -post_structural \
     -proc_dwi \
     -SC \
     -proc_rsfmri \
     		-regAffine -noFIX -regress_WM_CSF  \
     		-mainScanStr task-rest_acq-1400_bold \        
     -QC_subj
i have tried to manually assign the main dwi file, but it didn't work. could you help to find the solution?

**Comment by ajschadler12** [comment]
Hi: I believe you said you attempted to use the option `-dwi_main`, is that correct? what is the error output you get when using this to set the main scan?

**Comment by rcruces** [comment]
I'm sorry for the late response. Could you show me more about your bids `dwi/` main organization?

**Comment by rcruces** [comment]
The QC reports had an issue and the html file was deprecated. The new version solve all related issues. 

`v0.2.0 Northern flicker` https://github.com/MICA-MNI/micapipe/releases/tag/v0.2.0
