### ISSUE TITLE
MPC surface ordering distorted

### ISSUE THREAD

**Issue by rb643** [MICA-MNI/micapipe#52]
When running the micapipe container with the MPC module it appears that for some subjects and sessions my surface are not ordered correctly resulting in wrong lateralised correlation matrices, see the attached screenshots of the intensity profiles and resulting correlation matrices for two sessions of the same subject. This does not always happen in the same manner (i.e., the misordering of surfaces isn't consistent in the same way across subjects). 

My suspicion is that the surfaces are not created in the proper temporal order (or at least something is failing in line 158 of 03_MPC.sh). Unfortunately as I am running the containerised default version all individual surface files are removed so I can't check that assumption without running the code step by step. 

If there is an easy fix that could be plugged into the already run data (i.e., all freesufer and other registrations look totally fine and I would hate to rerun) then that would be much appreciated.

![Screenshot 2022-08-23 at 11 53 17](https://user-images.githubusercontent.com/10026949/186149633-5ee4cc7a-2009-4f06-b3a5-01d1a37a9229.png)

**Comment by rcruces** [comment]
I believe that this issue could be due to bad registrations, we also found this in some cases in some datasets. This issue was fix in the version [0.1.3](https://github.com/MICA-MNI/micapipe). We are currently building a new container with the FIX.

Thank you for your comment

**Comment by rcruces** [comment]
I've seen something similar before and I think is an issue more related with the registration between the qMRI and the freesurfer space. could you please check the registration of sub-01_ses-02 between:
${subject_dir}/anat/sub-01_ses-02_space-fsnative_desc-micro.nii.gz
and
${subject_dir}/anat/sub-01_ses-02_space-fsnative_t1w.nii.gz

where:
subject_dir: is the path to the micapipe/sub-01/ses-02

**Comment by rcruces** [comment]
This issue was fixed in the `v0.1.5` and registrations were improved and optimized for better performance in `v0.2.0`.

We invite you to use the newest version of the pipeline: https://github.com/MICA-MNI/micapipe/releases/tag/v0.2.0
