### ISSUE TITLE
ReadTheDocs Singularity issues/errors

### ISSUE THREAD

**Issue by thomshaw92** [MICA-MNI/micapipe#53]
* A couple of singularity command errors in the readthedocs

Currently:
 singularity run --cleanenv /my_images/micapipe-<version>.simg \
    -B path/to/your/bids_dataset:/bids_dataset:ro \
    -B path/to/your/bids_dataset/derivatives:/output_directory \
    -B path/to/your/working_directory:/tmp \
    -B path/to/your/freesurfer_license_file.txt:/opt/freesurfer-6.0.0/freesurfer_license_file.txt \
    micapipe<version>.simg \
    -bids /bids_dataset \
    -out /output_directory \
    -all -ses 01 \
    -threads 10 -tracts 10M

Should be changed to: 
 **singularity run --cleanenv  \**
    -B path/to/your/bids_dataset:/bids_dataset:ro \
    -B path/to/your/bids_dataset/derivatives:/output_directory \
    -B path/to/your/working_directory:/tmp \
    **-B path/to/your/freesurfer_license_file.txt:/opt/freesurfer-6.0.0/license.txt \** 
    **/path/to/container/micapipe<version>.simg \**
    -bids /bids_dataset \
    -out /output_directory \
    -all -ses 01 \
    -threads 10 -tracts 10M
:)

**Comment by rcruces** [comment]
Thanks for this comment, we fixed with the acceptance of the paper!!
https://micapipe.readthedocs.io/en/latest/pages/01.install/index.html
