### ISSUE TITLE
Incorporate FastSurfer

### ISSUE THREAD

**Issue by thomshaw92** [MICA-MNI/micapipe#54]
*   **What is the current behaviour?**  
* Freesurfer is slow and fix_topology is a problem.
* 
*   **What is the motivation / use case for changing the behaviour?**  
* 
*  Speedup, no vertex correction issues in fix_topology 

*   **Other information**  
FastSurfer https://deep-mi.org/research/fastsurfer/ would be a great alternative to Freesurfer cortical parc. and segmentation. 
https://github.com/deep-mi/FastSurfer
Drawbacks: It resamples T1w images to 1mm iso if they are hires - could include an option for choosing either stream (free vs fastsurfer)

**Comment by rcruces** [comment]
We hear you! and we are working in the incorporation of `fastsurfer` as well as other CNN based strategies to decrease the processing time of the pipeline and accuracy. We still have some issues to solve and it will take some time for this future release. Currently you can follow the implementation on our development branch.

**Comment by rcruces** [comment]
This and other great features were already added into our latest release please have a look!!

https://github.com/MICA-MNI/micapipe/releases/tag/v0.2.0
