### ISSUE TITLE
Results from auto_tract 

### ISSUE THREAD

**Issue by HEEHWANWANG** [MICA-MNI/micapipe#55]
Hi, I'm using auto_tract standalone pipeline to do bundle segmentation with whole-brain tractogram we estimated before.
Tractograms were estimated with matrix3 iFOD2. 
When I run auto_tract pipeline, however, there were no streamline counted as Fornix of both hemisphere. 
I think it is weird because when I open tractogram files, there were streamlines on the Fornix
Are there any tips or cautions I need to know for running auto_tract pipeline?

**Comment by ajschadler12** [comment]
How does the global tractogram look? You can keep it for some runs by specifying `micapipe <subject_args> -SC -keep_tck`. My only other suggestion would be to inspect the distortion correction. 
@rcruces , can you advise on how to check the registration between the diffusion data and the auto-tract template?

**Comment by rcruces** [comment]
I will close this issue due to lack of response if you have further inquires please don't hesitate to open a new one.
