### ISSUE TITLE
res-fMRI FC - missing ROI

### ISSUE THREAD

**Issue by Liz-Yuanxi-Lee** [MICA-MNI/micapipe#56]
*   **What is the current behavior?**   I have generated FC matrices with micapipe (singularity). Some of them contain 450 rows (which is the correct number for Schaefer-400), yet some of them contain 449 rows. This appeared to be the case for 5 out of 66 sessions. 
*   **Please provide the steps to reproduce and if possible a minimal demo of the problem**  I have run Freesurfer recon-all first, then the rest of the analysis with micapipe.
*   **What is the expected behavior?**  For instance, for Schaefer-400, there should 450 rows in the FC file.
*   **Please tell us about your computing environment:**  HPC, singularity.
*   **Other information**

**Comment by rcruces** [comment]
I'm sorry for the very late response, this issue happened before and apparently was and encoding error beyond the pipeline that could happen randomly.

On our new pipeline we are saving the matrices as GIFTI files to maintain consistency on the outputs we invite you to try it.

https://github.com/MICA-MNI/micapipe/releases/tag/v0.2.0
