### ISSUE TITLE
Rerun `-proc_dwi` with `-autotract`, fails because TCK is not regenerated.

### ISSUE THREAD

**Issue by ajschadler12** [MICA-MNI/micapipe#57]
*   **What is the current behavior?**
    * Run `-proc_dwi` without `-autotract` and without `-keep_tck`. (Exit successfully)
    * Rerun `-proc_dwi` with `-autotract`.
    * AutoTract exits due to lack of `tck` tractogram

* **Suggested fix**
    * Regenerate `tck` tractogram if not detected before `-autotract` call.

**Comment by rcruces** [comment]
A quick solution would be to erase the outputs of `-SC` and re run it with autotract. If this behaviour continues please let us know and we will fix it. Also we invite you to use the newest release `v0.2.0 Northen Flicker` https://github.com/MICA-MNI/micapipe/releases/tag/v0.2.0
