### ISSUE TITLE
building micapipe in docker on MacOS M1

### ISSUE THREAD

**Issue by slusna-dominika** [MICA-MNI/micapipe#59]
Hi all, 

when trying to run micapipe on my MacOS Monterey (12.2.1) with M1, I get an error relating to arm-based system of Mac since micapipe requires a linux/amd64 platform. 
One solution suggested on the net is to build micapipe before using it and so I have run `docker build https://github.com/MICA-MNI/micapipe.git --platform linux/amd64`
It started to build nicely installing several dependencies, but got stuck on step 6/23 when building FSL python environment:

#### error message #####
```
[ 6/23] RUN bash -c 'bash /opt/fsl-6.0.0/etc/fslconf/fslpython_install.sh -f /opt/fsl-6.0.0':                                                                
#8 8.533 Stage 1                                                                
#8 8.533 By installing this python distribution you agree to the license terms in
#8 8.533 /opt/fsl-6.0.0/fslpython/LICENSE.txt
100%.758 
#8 42.70 Stage 2
100%5.15 
#8 882.4 /opt/fsl-6.0.0/etc/fslconf/fslpython_install.sh: line 203:   759 Killed                  FSLDIR=$fsl_dir "${miniconda_bin_dir}/conda" env create -f "${script_dir}/fslpython_environment.yml" 2>> "${miniconda_install_log}"
#8 882.4        761 Done                    | ${script_dir}/progress.sh 133 ${quiet} >> "${miniconda_install_log}"
#8 882.4 Failed to create FSL Python environment - see /tmp/fslpythonesRS/fslpython_miniconda_installer.log for details
------
executor failed running [/bin/sh -c bash -c 'bash /opt/fsl-6.0.0/etc/fslconf/fslpython_install.sh -f /opt/fsl-6.0.0']: exit code: 4
```

M1 users, any suggestions on how to make micapipe build/run?

Thank you, 
Dominika

**Comment by rcruces** [comment]
We recommend you to download the container from `dockerhub` instead of trying to build it. `micapipe` has a complex environment and requires a lot of memory and time to build.

https://hub.docker.com/r/micalab/micapipe
