### ISSUE TITLE
Include option to disable bvalue scaling

### ISSUE THREAD

**Issue by ajschadler12** [MICA-MNI/micapipe#62]
*   **What is the current behaviour?**  
Micapipe uses default behavior of mrconvert, which includes bvalue scaling.

*   **What is the motivation / use case for changing the behaviour?**  
For ABCD multishell RSI sequences, bvalue-scaling leads to [incorrect DTI estimation](https://community.mrtrix.org/t/dwi2tensor-fa-differs-from-dtifit-fa/6345/2). Allowing for an option to not scale bvalues in mrconvert would make the DTI pipeline much more flexible.

**Comment by rcruces** [comment]
Hello, thank you for the observation, could you please provide us with the command that would not apply the rescaling or the bvalues? or are you referring to the `BZeroThreshold` used in the processing? because indeed the default BZeroThreshold is set to 61 but this behaviour could be customize. thank you

**Comment by ajschadler12** [comment]
You can disable bvalue scaling by adding `-bvalue_scaling no` to mrconvert when converting to mif.
E.g.
`mrconvert -bvalue_scaling no -fslgrad sub-abcd_ses-1_dir-AP_dwi.bvec sub-abcd_ses-1_dir-AP_dwi.bval sub-abcd_ses-1_dir-AP_dwi.nii.gz sub-abcd_ses-1_dir-AP_dwi.mif`

**Comment by ajschadler12** [comment]
Hi, yes, you will need to append `-bvalue_scaling no` to `mrconvert` when initially converting from nifti to mif.
E.g.
```
mrconvert -bvalue_scaling no -fslgrad sub-abcd_ses-01_dir-AP_dwi.bvec sub-abcd_ses-01_dir-AP_dwi.bval sub-abcd_ses-01_dir-AP_dwi.nii.gz sub-abcd_ses-01_dir-AP_dwi.mif
```

Dr. Tournier left an [in-depth comment](https://community.mrtrix.org/t/dwi2tensor-fa-differs-from-dtifit-fa/6345/9?u=ajschadler12) on why bvalue scaling might fail in some settings, particularly our data.

**Comment by rcruces** [comment]
Thank you for the observation, we added this feature on the latest v0.1.5 version of the pipeline this week. We are still building a new docker container updated.

**Comment by rcruces** [comment]
The docker was successfully built and this option is include in the versions `v0.1.5` and `v0.2.0`
