### ISSUE TITLE
Final LUT Entry for Schaefer 1000?

### ISSUE THREAD

**Issue by benjaminsipes** [MICA-MNI/micapipe#65]
Firstly, thank you all for creating this phenomenal resource! I'm excited to use it!

I was looking through the LUT files for the Schaefer parcellations, and I noticed that the final entry (1002) for the Schaefer-1000 atlas is missing. I also noticed that the penultimate entry was listed as the control network, which broke from the general pattern of having default network regions last. 

Any clarification on these network labels here would be greatly appreciated!

**Comment by rcruces** [comment]
Thank you so much for your observation. As a matter of fact we did note some inconsistencies in the labeling of few parcellations, that might be related to this issue. We will start a inventigation to solve this issue (@alexander-ngo, @royj23, @rcruces  )
This are the other pacellations were we observed possible indexing issues:
economo 

- FC schaeffer-100 indexing
- GD scheffer-1000 RIGHT indexig
- GD scheffer 700 indexing
- GD scheffer 900 indexing

**Comment by royj23** [comment]
Hi @benjaminsipes, the LUTs were generated from the annotation labels provided by Thomas Yeo's group on their public github. We specifically used the files "lh.Schaefer2018_1000Parcels_7Networks_order.annot" and "rh.Schaefer2018_1000Parcels_7Networks_order.annot". 

Looking at the annotation labels for the right hemisphere, it indeed seems that the last two entries are assigned to the control network (not sure why the label of the last entry was omitted in our LUT, we can correct this). As we use an existing parcellation, we chose not to alter the labels or indices. Hope this helps!
