### ISSUE TITLE
micapipe_check_dependency command not found

### ISSUE THREAD

**Issue by MarkNelson86** [MICA-MNI/micapipe#75]
Line 102 in 02_proc-dwi contains a command that doesn't work. Maybe it was an old subfunction?

**Comment by rcruces** [comment]
Could you be more specific about the version you are running? 

Also we invite you to use our newest release [`v0.2.0 Northern Flicker`](https://github.com/MICA-MNI/micapipe/releases/tag/v0.2.0)

**Comment by rcruces** [comment]
Maybe it was and old function, many minor issues and functionality were properly addressed and tested on the latest version release `v0.2.1`, which is already tagged on the github repository bbc4eabeea4fd83b8f28adb743d6b6da212af2ec  and online on the dockerhub [dockerhub](https://hub.docker.com/layers/micalab/micapipe/v0.2.1/images/sha256-7ae75a1a7621d001cc037fa0e3f9f1d3d5cc4fb2b7f2e2863eb5300de3f4b3e0?context=explore).

We thank you for your comments
