### ISSUE TITLE
Unable to pull version 0.2.0 from docker

### ISSUE THREAD

**Issue by AwesomeVortex** [MICA-MNI/micapipe#77]
I'm having trouble pulling the latest version of Micapipe, not sure if it's an issue on my end but I have no issues pulling other versions. After running "docker pull micalab/micapipe:v0.2.0" the error I keep getting is "Error response from daemon: manifest for micalab/micapipe:v0.2.0 not found: manifest unknown: manifest unknown". Anyone else having the same issue? I am running Docker on Windows

**Comment by rcruces** [comment]
Hello, the newest docker container is still under construction at our end and we have not deployed it yet. We will upload it as soon as it is ready. We will make an announcement when it's ready
We thank for your patience.

**Comment by AwesomeVortex** [comment]
Thank you!

**Comment by rcruces** [comment]
Hello, thanks for waiting.
The latest version `micapipe v0.2.0` _Northern Flicker_ was successfully uploaded to our [dockerhub](https://hub.docker.com/r/micalab/micapipe )
