### ISSUE TITLE
Documentation recommends container, no container exists

### ISSUE THREAD

**Issue by ikirker** [MICA-MNI/micapipe#8]
*   **What is the current behaviour?**  

Currently the documentation recommends installation via container:

<https://micapipe.readthedocs.io/en/latest/#reproducibility>:
> To encourage reproducibility and robustness of investigations using micapipe, we provide a fully containerized version of the pipeline in the form of a Docker container. Step-by-step tutorials are provided for bare metal and containerized installations. We encourage users to use containerized versions, offered through Docker and Singularity, given the large number of software dependencies used by the pipeline to handle multiple MRI data modalities.

<https://micapipe.readthedocs.io/en/latest/pages/01.install/index.html>:
> We offer three installation options for micapipe: two containerized versions (Docker and Singularity) as well as a bare-metal installation.

But no such container exists: the Docker instructions attempt to pull from an invalid source, and the Singularity instructions are a placeholder.

I'm not super-familiar with Docker in execution (I'm more familiar with Singularity), but here's what I get when I try to run the recommended Docker command on a fresh Ubuntu 20.04.1 system:

```
$ sudo docker pull MICA-MNI/micapipe:latest
invalid reference format: repository name must be lowercase

# In case it's only that the case is a problem:
$ sudo docker pull mica-mni/micapipe:latest
Error response from daemon: pull access denied for mica-mni/micapipe, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

# In case it's relevant:
$ docker --version
Docker version 20.10.6, build 370c289
```

Is it just that it's planned but no one's managed to get to it yet? I didn't see a Dockerfile in the repo or nearby in GitHub.

*   **What is the motivation / use case for changing the behaviour?**  

(To make the documentation correct and the containers available.)

*   **If relevant, please tell us about your computing environment:**

(Probably not relevant, but, Singularity and RHEL 7.6, with SGE.)
  
*   **Other information**  

(Happy to provide on request.)

**Comment by rcruces** [comment]
Hi, the container should be working now. We have also updated all our documentation!

**Comment by pesojka** [comment]
Hi, command for pulling singularity image isn't working: singularity pull shub://todo/todo...this is invalid.
https://micapipe.readthedocs.io/en/latest/pages/01.install/index.html
