### ISSUE TITLE
Faild using docker pull for install.

### ISSUE THREAD

**Issue by ZhyGao** [MICA-MNI/micapipe#83]
*   **What are you trying to do?
* I‘am trying to install the micapipe with docker.’  
*   **If you've tried running this with BrainSpace code already, how did you do so and what went wrong?**  Alway's download failed. I don't know why. But when pull other images, it works.
* 
![1687139766758](https://github.com/MICA-MNI/micapipe/assets/39367799/b505afcf-f142-42a4-8305-3c2a3f419876)

*   **Please tell us about your computing environment:**  
* Ubuntu
*   **Other information**

**Comment by rcruces** [comment]
Hello it looks like you had a network connectivity issue. 

Check your internet connection: Ensure that you have a stable internet connection and can access other websites or resources without any issues. If you're behind a firewall or proxy, make sure that Docker is configured correctly to work with the network environment.

Retry the pull command: Sometimes, network issues can be temporary. Retry the pull command after a few moments to see if the issue persists.

Use a VPN or proxy: If you're behind a restrictive network, try using a VPN or configuring Docker to work with a proxy server that allows the necessary connections for image downloads.

Check firewall settings: If you have a firewall enabled, ensure that it is not blocking Docker's network connections. Verify that the required ports for Docker (typically port 443 for HTTPS) are open and accessible.

We tried on our end pulling the image and it work with a stable network connection. I hope this is useful information.
