### ISSUE TITLE
-force flag on proc_dwi deletes proc_structural through post_structural output

### ISSUE THREAD

**Issue by ajschadler12** [MICA-MNI/micapipe#87]
*   **What is the current behavior?**  
    * Run `proc_structural`, `proc_surf`, `post_structural`, and `proc_dwi` with `-force` flag. `proc_dwi` failes because it overwrites subject output with empty directories.
*   **Please provide the steps to reproduce and if possible a minimal demo of the problem**  
    * Run `proc_structural` through `post_structural` then `proc_dwi`, all with `-force` flag. Structural processing will not delete output.
*   **What is the expected behavior?**  
    * `proc_dwi` with `-force` flag should only overwrite diffusion output. 
*   **Please tell us about your computing environment:**  
    * Linux.
    * Container: singularity built from v0.2.1 docker container.

**Comment by rcruces** [comment]
Hello, 

Indeed the `-force` flag is not specific per module. When you use it it will erase all the subject's directory and re-process everything. If for any reason you would like to erase a specific module before re-runing the option `-cleanup` is the one that will erase it.

If you want to erase a module created by `proc_dwi` use the following flags:
`micapipe -sub <SUB> -ses <SES> -cleanup -acqStr <DWI-NAME>  -proc_dwi`

It's a good observation that the option force should overwrite the module. We'll keep it in mind for future implementations.
