### ISSUE TITLE
Fastsurfer not running in containerized micapipe v0.2.2

### ISSUE THREAD

**Issue by araikes** [MICA-MNI/micapipe#89]
*   **What is the current behavior?**  
I downloaded `v0.2.2` today and attempted to process some data with it. `-proc_structural` runs but `-proc_surf` does not. I receive the error:

```
[ INFO ]..... FastSurfer: running the singularity image 
/opt/micapipe/functions/01_proc-surf.sh: line 150: singularity: command not found
```
The problem is here:
https://github.com/MICA-MNI/micapipe/blob/2c5b7e81d08c9890c3d046fedf885107fb47bd93/functions/01_proc-surf.sh#L133

because
```
-------------------------------------------------------------
	Surface processing
		micapipe v0.2.2 'Northern flicker', container_micapipe-v0.2.2 
-------------------------------------------------------------
```

**Comment by rcruces** [comment]
You are right, thanks for reporting this. The issue was fixed, please download the same container, we didn't updated the version only fixed the bug. But the dockerhub v0.2.2 was replaced with the corrected version.
