### ISSUE TITLE
 ERROR ]..... B0 threshold is not a valid integrer: DEFAULT

### ISSUE THREAD

**Issue by hoptman** [MICA-MNI/micapipe#99]
*   **What is the current behavior?**  
*   **Please provide the steps to reproduce and if possible a minimal demo of the problem**  
*   **What is the expected behavior?**  
*   **Please tell us about your computing environment:**  
*   **Other information**  
I am trying to run -proc_dwi. I have a *.bval file consisting of b=5, b=1495, and b=1500. There are no b=0 images.

When I run the docker command (v0.2.0)
docker run -ti --rm -v  `pwd`/bids_data:/bids -v `pwd`/micapipe:/out -v `pwd`/micapipe_tmp:/tmp -v /mnt/software/freesurfer/license.txt:/opt/licence.txt micalab/micapipe:v0.2.0 -bids /bids -out /out -fs_licence /opt/licence.txt -threads 3 -sub <subj> -ses ses-BAS1 -proc_dwi -dwi_main /mnt/home2/Rockland_sample/bids3/sub-<subj>/ses-BAS1/dwi/<subj>_ses-BAS1_dwi.nii 

I get the message [ERROR].... B0 threshold is not a valid inegrer: DEFAULT

I'm not sure how to get around this, and am stuck. 

I am running on a server with Ubuntu 20.04

**Comment by rcruces** [comment]
Hello, first of all sorry for the late reply. it looks like the arguments are misreaded by bash because `-dwi_main` is not mounted correctly. If your dataset is BIDS I think the correct code should be something like this:

```bash
docker run -ti --rm \
-v pwd/bids_data:/bids \
-v pwd/micapipe:/out \
-v pwd/micapipe_tmp:/tmp \
-v /mnt/software/freesurfer/license.txt:/opt/licence.txt micalab/micapipe:v0.2.0 \
-bids /bids -out /out \
-fs_licence /opt/licence.txt \
-threads 3 -sub -ses ses-BAS1 \
-proc_dwi -dwi_main  /bids/sub-/ses-BAS1/dwi/_ses-BAS1_dwi.nii
```

Also it seems that your subject argument is empty. -sub is a mandatory argument. It depends on the structure of your dataset naming.

**Comment by rcruces** [comment]
Did it work? I will close this issue for now. If you need further help please don't hesitate and re-open it.

best

**Comment by hoptman** [comment]
> Did it work? I will close this issue for now. If you need further help please don't hesitate and re-open it.
> 
> best

It worked! Thanks so much!!
